project_id = "avfafxojrijfsgsyimwx"

[functions.n8n-reservations]
verify_jwt = false

[functions.n8n-appointments]
verify_jwt = false

[functions.n8n-documents]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
